"""Add collection models

Revision ID: 5eda3a75a38c
Revises: 
Create Date: 2025-04-15 20:52:30.094517

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5eda3a75a38c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('loan_collections',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('officer_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('payment_type', sa.String(length=20), nullable=False),
    sa.Column('collection_date', sa.DateTime(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ),
    sa.ForeignKeyConstraint(['officer_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('project_fund_collections',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('officer_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('project_type', sa.String(length=50), nullable=False),
    sa.Column('collection_date', sa.DateTime(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ),
    sa.ForeignKeyConstraint(['officer_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('registration_fee_collections',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('officer_id', sa.Integer(), nullable=False),
    sa.Column('project_amount', sa.Integer(), nullable=False),
    sa.Column('member_amount', sa.Integer(), nullable=False),
    sa.Column('collection_date', sa.DateTime(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ),
    sa.ForeignKeyConstraint(['officer_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('welfare_collections',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('officer_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('purpose', sa.String(length=50), nullable=False),
    sa.Column('collection_date', sa.DateTime(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ),
    sa.ForeignKeyConstraint(['officer_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('service_fee_collections', sa.Column('notes', sa.Text(), nullable=True))
    op.alter_column('service_fee_collections', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=False)
    op.alter_column('service_fee_collections', 'group_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('service_fee_collections', 'officer_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('service_fee_collections', 'collection_date',
               existing_type=sa.DATETIME(),
               nullable=False)
    op.drop_index('ix_service_fee_collections_group_id', table_name='service_fee_collections')
    op.drop_index('ix_service_fee_collections_officer_id', table_name='service_fee_collections')
    op.drop_column('service_fee_collections', 'status')
    op.drop_column('service_fee_collections', 'service_type')
    op.drop_column('service_fee_collections', 'description')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('service_fee_collections', sa.Column('description', sa.TEXT(), nullable=True))
    op.add_column('service_fee_collections', sa.Column('service_type', sa.VARCHAR(length=64), nullable=False))
    op.add_column('service_fee_collections', sa.Column('status', sa.VARCHAR(length=20), nullable=True))
    op.create_index('ix_service_fee_collections_officer_id', 'service_fee_collections', ['officer_id'], unique=False)
    op.create_index('ix_service_fee_collections_group_id', 'service_fee_collections', ['group_id'], unique=False)
    op.alter_column('service_fee_collections', 'collection_date',
               existing_type=sa.DATETIME(),
               nullable=True)
    op.alter_column('service_fee_collections', 'officer_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('service_fee_collections', 'group_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('service_fee_collections', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=True)
    op.drop_column('service_fee_collections', 'notes')
    op.drop_table('welfare_collections')
    op.drop_table('registration_fee_collections')
    op.drop_table('project_fund_collections')
    op.drop_table('loan_collections')
    # ### end Alembic commands ###
